Added ManualClock to Test Module
JuulLabs/tuulbox pull request #204
Opened 2022-08-09 20:37 UTC by davidtaylor-juul

Closes #203

2022-08-09 21:29 UTC, twyatt requested changes

2022-08-09 21:29 UTC, twyatt commented on test/src/commonMain/kotlin/ManualClock.kt
> +) : Clock {
IMHO, we should drop the default time, unless there is a standard for this default?

```suggestion
public class ManualClock(
    private var time: Instant,
) : Clock {
```

_Library consumers can "fake" a default constructor, if desired:_

```kotlin
fun ManualClock() = ManualClock(defaultTime)
```

2022-08-10 19:35 UTC, twyatt approved these changes

2022-08-11 17:10 UTC, QuantumRand approved these changes

2022-08-11 17:16 UTC, merged